Repository AY2425S1-CS2103T-F14a-4/tp, pull requests merged in 2024-10, with the labels that each got.

#17 Add Zheng Jie's AboutUs details
  docs/AboutUs.md
  docs/team/krashkart.md
Labels: type.Chore, priority.Medium

#20 Update Justin's About Us docs
  docs/AboutUs.md
  docs/images/yooplo.png
  docs/team/justin.md
Labels: type.Chore, priority.Medium

#33 Update DG Use Cases
  docs/DeveloperGuide.md
Labels: type.Chore, priority.High, severity.VeryLow

#38 Update product scope
  docs/DeveloperGuide.md
Labels: type.Chore, priority.High, severity.Low

#37 Add user stories to Developer Guide
  docs/DeveloperGuide.md
Labels: type.Story, type.Chore, priority.High, severity.Low

#36 Update non-functional requirements
  docs/DeveloperGuide.md
Labels: type.Chore, priority.High, severity.Low

#40 Edit README.md
  README.md
  docs/images/Ui.png
Labels: type.Chore, priority.High, severity.VeryLow

#41 Rename Nguyen's png file
  docs/AboutUs.md
  docs/images/blackpanther9229.png
Labels: type.Chore, priority.High, severity.VeryLow

#42 Branch about us of Nguyen
  docs/AboutUs.md
  docs/team/blackpanther9229.md
Labels: priority.High

#54 Re-implement find by name command
  src/main/java/seedu/address/logic/commands/AbstractFindCommand.java
  src/main/java/seedu/address/logic/commands/FindByNameCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/test/java/seedu/address/logic/commands/FindByNameCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Labels: type.Chore, priority.High

#53 Implement duplicate email checking feature
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: type.Enhancement, priority.High

#57 Implement FindByEmailCommand Class
  src/main/java/seedu/address/logic/commands/AbstractFindCommand.java
  src/main/java/seedu/address/logic/commands/FindByEmailCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/test/java/seedu/address/logic/commands/FindByContactCommandTest.java
  src/test/java/seedu/address/logic/commands/FindByEmailCommandTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Labels: type.Enhancement, priority.High

#59 Add new method to support changing details of a Person
  src/main/java/seedu/address/model/person/Person.java
Labels: type.Enhancement, priority.High

#70 Branch Edit GUI
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/nus_logo.png
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
Labels: priority.Medium, severity.VeryLow, type.FunctionalityBug

#73 Delete FindCommand and remove dependencies
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
Labels: type.Chore, priority.Low

#81 Change README
  README.md
  docs/images/Ui.png
Labels: type.Chore, priority.Low

#89 Remove all traces of Address
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/CampusConnectTest.java
  src/test/java/seedu/address/model/person/AddressTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/TagContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Chore, priority.Low, severity.Low

#77 Attempt to update new edit command
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/CampusConnect.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
Labels: type.Bug, priority.High, severity.High

#96 Update new Junit Test for new adjustment in EditCommand
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
Labels: priority.Medium

#103 Add spacing between tags in UI display
  src/main/java/seedu/address/ui/PersonCard.java
Labels: priority.Medium, severity.VeryLow, type.FunctionalityBug, workload.low

#106 Update UML diagrams in DG
  docs/DeveloperGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/CommandClasses.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ParserClasses.puml
Labels: priority.Medium, type.DocumentationBug, workload.low

#114 Add Assertions to build.gradle
  build.gradle
Labels: type.Chore, priority.Low, workload.low

#123 Implement ArgumentTokenizer for the Find commands
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/test/java/seedu/address/logic/parser/CampusConnectParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Labels: priority.High, severity.Medium, type.FunctionalityBug, workload.medium

#124 Update UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/findAlexDavidResult.png
  docs/images/findBerniceCharlotteResult.png
  docs/images/helpMessage.png
Labels: priority.Low, type.DocumentationBug, workload.low

#136 Fix bugs while deleting tag
  src/main/java/seedu/address/model/ModelManager.java
Labels: type.Bug

#137 Disable data saving for list and find
  src/main/java/seedu/address/logic/LogicManager.java
Labels: type.Bug

#139 Implement constraints to Phone information
  docs/UserGuide.md
  src/main/java/seedu/address/model/person/Phone.java
  src/test/data/JsonSerializableCampusConnectTest/typicalPersonsCampusConnect.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindByPhoneCommandTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
  src/test/java/seedu/address/model/person/TagContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.Medium, type.FunctionalityBug, workload.low

#143 Create AddTagCommand and AddTagCommandParser
  src/main/java/seedu/address/logic/commands/AddTagCommand.java
  src/main/java/seedu/address/logic/parser/AddTagCommandParser.java
  src/main/java/seedu/address/logic/parser/CampusConnectParser.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
Labels: type.Enhancement, priority.High

#155 Update AddTag command sequence diagram
  docs/diagrams/AddTagSequenceDiagram.puml
  src/main/java/seedu/address/logic/commands/AddTagCommand.java
  src/main/java/seedu/address/logic/parser/AddTagCommandParser.java
Labels: priority.Medium

#165 Add test cases for AddTagCommand and its parser
  src/test/java/seedu/address/logic/commands/AddTagCommandTest.java
  src/test/java/seedu/address/logic/parser/AddTagCommandParserTest.java
Labels: type.Chore, priority.Medium, workload.medium
