Repository AY2425S1-CS2103T-F14a-4/tp, pull requests merged in 2024-11, with the labels that each got.

#185 Addtag command success incorrect display message
  src/main/java/seedu/address/logic/commands/AddTagCommand.java
Labels: priority.High, type.FunctionalityBug, workload.low, alpha-bug

#187 Fix small bug with display message.
  src/main/java/seedu/address/logic/commands/CategorizeTagCommand.java
Labels: alpha-bug

#193 Fix unit test cases
  src/test/java/seedu/address/logic/commands/AddTagCommandTest.java
Labels: priority.Low, severity.Low, type.FunctionalityBug, alpha-bug

#195 Delete Tag has no error message
  src/main/java/seedu/address/logic/parser/DeleteTagCommandParser.java
Labels: priority.High, type.FunctionalityBug, workload.low, alpha-bug

#199 Update add tag parser
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/parser/AddTagCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddTagCommandParserTest.java
Labels: alpha-bug

#188 Replace the invalid category example of "modules" with "acads"
  src/main/java/seedu/address/logic/commands/CategorizeTagCommand.java
Labels: severity.Low, alpha-bug

#200 Standardize error messages across commands
  src/main/java/seedu/address/logic/commands/AddTagCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTagCommand.java
  src/main/java/seedu/address/logic/commands/FindByEmailCommand.java
  src/main/java/seedu/address/logic/commands/FindByNameCommand.java
  src/main/java/seedu/address/logic/commands/FindByPhoneCommand.java
  src/main/java/seedu/address/logic/commands/FindByTagCommand.java
  src/main/java/seedu/address/logic/commands/SuperFindCommand.java
  src/main/java/seedu/address/logic/parser/AddTagCommandParser.java
  src/test/java/seedu/address/logic/commands/FindByEmailCommandTest.java
  src/test/java/seedu/address/logic/commands/FindByNameCommandTest.java
  src/test/java/seedu/address/logic/commands/FindByPhoneCommandTest.java
  src/test/java/seedu/address/logic/commands/FindByTagCommandTest.java
  src/test/java/seedu/address/logic/parser/CampusConnectParserTest.java
Labels: severity.VeryLow, type.FunctionalityBug, workload.low, alpha-bug

#191 Inconsistent ordering of tags
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/ui/PersonCard.java
Labels: priority.High, type.FunctionalityBug, workload.low, alpha-bug

#208 Tag categories must be saved properly in json
  docs/UserGuide.md
  src/main/java/seedu/address/model/tag/TagCategory.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/test/java/seedu/address/model/tag/TagCategoryTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: priority.High, type.FunctionalityBug, workload.medium

#223 Change landing page
  docs/images/Ui.png
  docs/index.md
Labels: priority.High, type.DocumentationBug, workload.low

#228 Implement update for changing the tag labels color in the UI
  src/main/java/seedu/address/model/tag/TagCategory.java
  src/main/java/seedu/address/ui/PersonCard.java
Labels: priority.Medium, alpha-bug

#229 Make ResultDisplay taller
  src/main/java/seedu/address/logic/commands/SuperFindCommand.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/TagListPanel.fxml
Labels: priority.Low, type.FunctionalityBug, workload.low

#222 Implement the fix for multiple input tags in cattag command
  src/main/java/seedu/address/logic/commands/CategorizeTagCommand.java
  src/main/java/seedu/address/logic/parser/CategorizeTagCommandParser.java
  src/test/java/seedu/address/logic/commands/CategorizeTagCommandTest.java
  src/test/java/seedu/address/logic/parser/CategorizeTagCommandParserTest.java
Labels: priority.High, alpha-bug

#224 Change command classes in DG
  docs/DeveloperGuide.md
  docs/diagrams/CommandClasses.puml
  docs/diagrams/CommandClassesOriginal.puml
Labels: priority.High, type.DocumentationBug, workload.medium

#225 Add effort appendix to DG
  docs/DeveloperGuide.md
Labels: priority.High, type.DocumentationBug, workload.low

#236 Branch hyperlink
  docs/UserGuide.md
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/images/nus_mascot.png
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
Labels: priority.Low, type.FunctionalityBug, workload.low

#241 Improve ug
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/desktop.ini
  docs/images/findBerniceCharlotteResult.png
  docs/images/findBerniceIS1108Result.png
  docs/images/findFloorRunResult.png
  docs/images/helpMessage.png
Labels: priority.High, type.DocumentationBug, workload.medium

#253 Cattag displaying bug
  docs/UserGuide.md
  docs/images/cattagResponse.png
  src/main/java/seedu/address/logic/commands/CategorizeTagCommand.java
Labels: priority.Medium, alpha-bug

#266 Edit Readme Acknowledgements
  README.md
Labels: severity.VeryLow, type.DocumentationBug

#263 Add UG detail of deltag
  docs/UserGuide.md
Labels: alpha-bug

#269 Add terms to glossary
  docs/DeveloperGuide.md
Labels: priority.Medium, type.DocumentationBug, workload.low

#355 Add SuperFindCommand Test cases
  src/main/java/seedu/address/logic/commands/SuperFindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/EmailContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/PhoneContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/TagContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/SuperFindCommandTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Labels: priority.Medium, severity.VeryLow

#359 Fix issues raised in PE-D
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/images/EmptyUi.png
Labels: type.DocumentationBug

#277 Update manual testing guide for addtag command
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Enhancement, type.DocumentationBug, workload.medium

#366 Remove access bullet point
  docs/UserGuide.md
Labels: type.DocumentationBug

#361 Fix DG PE-D issues
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.DocumentationBug

#368 Attempt to fix UG FAQ issue
  docs/UserGuide.md
Labels: type.DocumentationBug

#369 Attempt 2 to fix UG FAQ
  docs/UserGuide.md
Labels: type.DocumentationBug
